kind: pipeline
name: default

steps:
  - name: deploy-all-dev
    image: node:10.15-alpine
    environment:
      STAGE: dev
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    commands:
      - ./build.sh
    when:
      event: push
      branch: master